# Site settings
title: Dipl.-Med. Oda Kautzky
email: your-email@domain.com
url: https://www.hautarztpraxis-kautzky.de
keywords: "your keywords, separated by commas"
subtitle: "Ihre Hautarztpraxis in Böhlen"
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
meta_author: Kautzky Oda

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c9a0dc #80B3FF
  primary-rgb: "201,160,220" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Oda Kautzky
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Jahnstraße 21
  - line: 04564 Böhlen

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
opening:
  - day: Montag
    time: 09:00–12:00 und 16:00–18:00
    note: Mit Termin
  - day: Dienstag
    time: 09:00-10:00
    note: Offene Sprechstunde
  - day: Mittwoch
    time: 09:00–12:00 und 16:00–18:00
    note: Normale Sprechstunde
  - day: Donnerstag
    time: Geschlossen
    note:
  - day: Freitag
    time: 08:00–11:00
    note: Normale Sprechstunde

announcements:
  - title: Geänderte Öffungszeiten
    date: 11.11.2021
    message: |
      Im Dezember haben wir andere Öffnungszeiten die sie hier sehen...
  - title: Neue Telefonnummer
    date: 06.12.2021
    message: |
      Wir sind bald unter einer anderen Nummer erreichbar
